### ISSUE TITLE
not a crash.  Intended Mod Interaction/behavior?  Testing a skyblock map with Ex Nihilo 2.  using a crucible from EN to melt cobble into lava causing polution with poison effect and death.  this was the first bucket of lava made so it is not a large production.  does the pollution dissipate naturally or is this a permanent end for a skyblock type map?

### ISSUE THREAD

**Issue by popps73x** [Artem226/MinecraftEcologyMod#1]
Makes sure these boxes are checked before submitting your issue!

1.Check, that your JVM has enough RAM(If there are "OutOfMemoryError");
2.Check, that there aren't issues like this;
3.Check, that only my mod causes crash;
4.Please, write issues on English;
5.Also, it's better to attach crash-report/log;
6.You can send suggestions too, but don't send already exist stuff

**Comment by Artem226** [comment]
Yes, pollution goes away from polluted chunks, but does it slowly. Anyway, it's needed rebalance of the mod.
