### ISSUE TITLE
[1.12.2] When your Mod is installed, ThutTech Elevators start desyncing

### ISSUE THREAD

**Issue by D3nnis3n** [Artem226/MinecraftEcologyMod#12]
See this issue on Thut-GitHub:
As soon as EcologyMod is active, Desyncs are Happening, if your mod is removed, they stop immediatly.

https://github.com/Thutmose/Thut/issues/69

**Comment by VirtualGaming1** [comment]
what thuttech elevators version is it?
it might be on there side

**Comment by D3nnis3n** [comment]
6.0.8.2 at this moment. I'll Need to re-test this issue on the Weekend, but i got an infected ear at the Moment and am out of order.

**Comment by D3nnis3n** [comment]
I can no longer reproduce this issue. :)
