### ISSUE TITLE
1.10.2 Furnace Explodes

### ISSUE THREAD

**Issue by scottosx** [Artem226/MinecraftEcologyMod#13]
Furnace explodes when cooking even a single piece of food. Is this intended behavior? If so, is there a way to turn it off or make it much less likely?

I am trying this mod for the first time for a modpack and this is a show stopper in early game.

**Comment by Artem226** [comment]
Hello, @scottosx!
This is surely not intended. I've added a furnace explosion just to test the furnace pollution behavior and unfortunately forgot to remove it.
The bug will be fixed at the nearest time!

**Comment by Artem226** [comment]
Fixed

**Comment by scottosx** [comment]
Thanks for the quick fix! I didn't think it was as intended. Still, the mechanic is interesting and I can see that it could be a consequence of very high pollution levels. Are you looking at something like that? It would need to be configurable of course.
