### ISSUE TITLE
[MC1.12.2] [v1.2.1.0] Server Crashing at startup after a crash during a server is running

### ISSUE THREAD

**Issue by VirtualGaming1** [Artem226/MinecraftEcologyMod#14]
Hay I had a crash happen on my server on a server tick loop and it crashed
[crash-2017-11-11_11.12.57-server.txt](https://github.com/Artem226/MinecraftEcologyMod/files/1464043/crash-2017-11-11_11.12.57-server.txt)
and then now i can not run my server because it crashing on startup
[crash-2017-11-11_19.37.10-server.txt](https://github.com/Artem226/MinecraftEcologyMod/files/1464045/crash-2017-11-11_19.37.10-server.txt)
My guess is that the file that it try to load got crupted 
This is on my public server of my modpack and do not know if it is safe to remove the mod for with out damaging my world are there any quick fix that i could do. my server do have a back up mod so are there a file that i can replace to get it working again?

**Comment by VirtualGaming1** [comment]
i just replaced the pollutionMap.json and will do further testing, so one of the chunk/node had a bad data or incomplete but would im going to keep this open so you can see and able to make a fix to prevent this of happening again.
Let me know what you think and i am using Creeperhost server to give you a heads up.

**Comment by D3nnis3n** [comment]
This issue seems fixed. I had the same before, now it crashed again (#15) but this issue does no longer occur. It starts up fine.
