### ISSUE TITLE
Server Crash with amped up Vent Rotation

### ISSUE THREAD

**Issue by LokeYourLord** [Artem226/MinecraftEcologyMod#26]
I basically receive this crash when trying to break an Advanced Filter, and the only way I can remove it (because it always comes back if I hit it), is by using WorldEdit to completely clear the marked area.

Log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-45.jar)
  mysttmtgravitymod (UpAndDownAndAllAround-1.12.2-2.8.0.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b135.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.5.7.jar)
  EcomodLoadingPlugin (EcologyMod-1.12.2-1.4.0.0.jar)
  GottaGoFastLoader (gottagofast-1.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 15.01.18 02:43
Description: Exception ticking world

java.lang.NoSuchFieldError: vent_rotation
	at ecomod.common.tiles.TileAdvancedFilter.<init>(TileAdvancedFilter.java:58)
	at ecomod.common.blocks.BlockAdvancedFilter.func_149915_a(BlockAdvancedFilter.java:61)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:780)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:798)
	at net.minecraft.world.World.func_175625_s(World.java:2379)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at ecomod.common.tiles.TileAdvancedFilter.<init>(TileAdvancedFilter.java:58)
	at ecomod.common.blocks.BlockAdvancedFilter.func_149915_a(BlockAdvancedFilter.java:61)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:780)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:798)
	at net.minecraft.world.World.func_175625_s(World.java:2379)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['LokeYourLord'/308, l='world', x=55,11, y=55,26, z=-75,61]]
	Chunk stats: ServerChunkCache: 649 Drop: 0
	Level seed: 6837080478920543034
	Level generator: ID 06 - hcisland, ver 0. Features enabled: true
	Level generator options: {"seaLevelOverride":48,"oceanBlockOverride":"minecraft:lava","island":{"treesPerChunk":7,"grassPerChunk":4,"flowersPerChunk":25,"generateFalls":false,"generateLakes":false,"generateLakesLava":false,"radius":34,"stoneBlock":"minecraft:stone","layers":["1, minecraft:grass","5, minecraft:dirt","1, minecraft:clay","2, minecraft:gravel"],"layersUnderwater":[]},"islandBeach":{"cactiPerChunk":12,"generateFalls":false,"generateLakes":false,"generateLakesLava":false,"radius":12,"stoneBlock":"minecraft:stone","layers":["8, minecraft:sand","2, minecraft:sandstone","1, minecraft:clay","2, minecraft:gravel"],"layersUnderwater":["2, minecraft:obsidian","1, minecraft:sandstone","1, minecraft:hardened_clay","2, minecraft:netherrack"]},"ocean":{"radius":48,"stoneBlock":"minecraft:stone","layers":["8, minecraft:netherrack"],"layersUnderwater":["2, minecraft:obsidian","1, minecraft:sandstone","1, minecraft:hardened_clay","4, minecraft:netherrack"]},"wasteland":{"generateFire":true,"generateFalls":true,"generateLakes":false,"generateLakesLava":true,"radius":30,"stoneBlock":"minecraft:netherrack","layers":["8, minecraft:netherrack"],"layersUnderwater":["1, minecraft:obsidian","1, minecraft:sandstone","1, minecraft:hardened_clay","8, minecraft:netherrack"]},"wastelandBeach":{"generateFire":true,"generateFalls":true,"generateLakes":false,"generateLakesLava":true,"radius":5,"stoneBlock":"minecraft:netherrack","layers":["16, minecraft:netherrack"],"layersUnderwater":["1, minecraft:obsidian","1, minecraft:sandstone","1, minecraft:hardened_clay","10, minecraft:netherrack"]},"wastelandEdge":{"generateFire":true,"generateFalls":true,"generateLakes":true,"generateLakesLava":true,"radius":8,"stoneBlock":"minecraft:stone","layers":["8, minecraft:netherrack","2, minecraft:gravel"],"layersUnderwater":["8, minecraft:netherrack"]}}
	Level spawn location: World: (8,77,2), Chunk: (at 8,4,2 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 579740 game time, 579740 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 3455 (now: false), thunder time: 22931 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1986893040 bytes (1894 MB) / 2629828608 bytes (2508 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 24, tallocated: 190
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version          | Source                                                      | Signature                                |
	|:--------- |:-------------------- |:---------------- |:----------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2           | minecraft.jar                                               | None                                     |
	| UCHIJAAAA | mcp                  | 9.42             | minecraft.jar                                               | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99        | forge-1.12.2-14.23.1.2555-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.1.2555     | forge-1.12.2-14.23.1.2555-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | advancedrocketrycore | 1                | minecraft.jar                                               | None                                     |
	| UCHIJAAAA | gottagofast          | 1.0              | gottagofast-1.0.jar                                         | None                                     |
	| UCHIJAAAA | securitycraft        | v1.8.3           | [1.12.x] SecurityCraft v1.8.3.jar                           | None                                     |
	| UCHIJAAAA | redstoneflux         | 2.0.1            | RedstoneFlux-1.12-2.0.1.2-universal.jar                     | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore             | 4.3.7            | CoFHCore-1.12.2-4.3.7.25-universal.jar                      | None                                     |
	| UCHIJAAAA | libvulpes            | 0.2.7.-24        | LibVulpes-1.12.2-0.2.7-24-universal.jar                     | None                                     |
	| UCHIJAAAA | advancedrocketry     | 1.2.6.-45        | AdvancedRocketry-1.12.2-1.2.6-45.jar                        | None                                     |
	| UCHIJAAAA | appliedenergistics2  | rv5-stable-3     | appliedenergistics2-rv5-stable-3.jar                        | None                                     |
	| UCHIJAAAA | bdlib                | 1.14.3.12        | bdlib-1.14.3.12-mc1.12.2.jar                                | None                                     |
	| UCHIJAAAA | ae2stuff             | 0.7.0.4          | ae2stuff-0.7.0.4-mc1.12.2.jar                               | None                                     |
	| UCHIJAAAA | aroma1997core        | 2.0.0.0.b135     | Aroma1997Core-1.12.2-2.0.0.0.b135.jar                       | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aromabackup          | 2.1.1.3.b89      | AromaBackup-1.12.2-2.1.1.3.b89.jar                          | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aromabackuprecovery  | 2.1.1.3.b89      | AromaBackup-1.12.2-2.1.1.3.b89.jar                          | None                                     |
	| UCHIJAAAA | attributefix         | 1.0.1            | AttributeFix-1.12.2-1.0.1.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | bedrockreplacer      | 7.0.2            | BedrockReplacer-Forge-7.0.2.jar                             | None                                     |
	| UCHIJAAAA | codechickenlib       | 3.1.5.331        | CodeChickenLib-1.12.2-3.1.5.331-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | cofhworld            | 1.0.2            | CoFHWorld-1.12.2-1.0.2.10-universal.jar                     | None                                     |
	| UCHIJAAAA | cyberware            | 0.2.10.5         | cyberware-1.12.2-0.2.10.5.jar                               | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAAAA | dimensionloader      | 1.12.2-1.0       | dimensionloader-1.12.2-1.0.jar                              | None                                     |
	| UCHIJAAAA | ecomod               | 1.12.2-1.4.0.0   | EcologyMod-1.12.2-1.4.0.0.jar                               | None                                     |
	| UCHIJAAAA | enderstorage         | 2.4.2.126        | EnderStorage-1.12.2-2.4.2.126-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | extracells           | 2.5.10           | ExtraCells-1.12.2-2.5.10a47.jar                             | None                                     |
	| UCHIJAAAA | com.boydti.fawe      | 3.5.1            | FastAsyncWorldEdit-forge112-17.12.15-0dbb617-949-18.0.6.jar | None                                     |
	| UCHIJAAAA | forgivingvoid        | 1.0.5            | ForgivingVoid_1.12-1.0.5.jar                                | None                                     |
	| UCHIJAAAA | grue                 | 1.3.5            | Grue-1.12-1.3.5.jar                                         | None                                     |
	| UCHIJAAAA | hammercore           | 1.9.5.7          | HammerCore-1.12.2-1.9.5.7.jar                               | None                                     |
	| UCHIJAAAA | hcisland             | 0.2.2            | hcisland-0.2.2.jar                                          | None                                     |
	| UCHIJAAAA | ichunutil            | 7.1.4            | iChunUtil-1.12.2-7.1.4.jar                                  | None                                     |
	| UCHIJAAAA | igwmod               | 1.4.3-14         | IGW-Mod-1.12.2-1.4.3-14-universal.jar                       | None                                     |
	| UCHIJAAAA | jei                  | 4.8.5.138        | jei_1.12.2-4.8.5.138.jar                                    | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2     | journeymap-1.12.2-5.5.2.jar                                 | None                                     |
	| UCHIJAAAA | longfallboots        | 1.2.1a           | longfallboots-1.2.1a.jar                                    | None                                     |
	| UCHIJAAAA | mekanism             | 1.12.2-9.4.3.330 | Mekanism-1.12.2-9.4.3.330.jar                               | None                                     |
	| UCHIJAAAA | mekanismgenerators   | 9.4.3            | MekanismGenerators-1.12.2-9.4.3.330.jar                     | None                                     |
	| UCHIJAAAA | mekanismtools        | 9.4.3            | MekanismTools-1.12.2-9.4.3.330.jar                          | None                                     |
	| UCHIJAAAA | minemenu             | 1.6.3            | MineMenu-1.12.2-1.6.3-universal.jar                         | None                                     |
	| UCHIJAAAA | netherportalfix      | 5.3.13           | NetherPortalFix_1.12.1-5.3.13.jar                           | None                                     |
	| UCHIJAAAA | nuclearcraft         | 2.8d             | NuclearCraft-2.8d--1.12.2.jar                               | None                                     |
	| UCHIJAAAA | thermalfoundation    | 2.3.7            | ThermalFoundation-1.12.2-2.3.7.18-universal.jar             | None                                     |
	| UCHIJAAAA | thermalexpansion     | 5.3.7            | ThermalExpansion-1.12.2-5.3.7.31-universal.jar              | None                                     |
	| UCHIJAAAA | omlib                | 3.0.0-133        | omlib-1.12.2-3.0.0-133.jar                                  | None                                     |
	| UCHIJAAAA | openmodularturrets   | 3.0.0-230        | openmodularturrets-1.12.2-3.0.0-230.jar                     | None                                     |
	| UCHIJAAAA | portalgun            | 7.0.0            | PortalGun-1.12.2-7.0.1.jar                                  | None                                     |
	| UCHIJAAAA | redstonearsenal      | 2.3.7            | RedstoneArsenal-1.12.2-2.3.7.18-universal.jar               | None                                     |
	| UCHIJAAAA | redstonepaste        | 1.7.5            | redstonepaste-mc1.12-1.7.5.jar                              | None                                     |
	| UCHIJAAAA | refinedrelocation    | 4.2.16           | RefinedRelocation_1.12.2-4.2.16.jar                         | None                                     |
	| UCHIJAAAA | servertickmonitor    | 3.0.0            | ServerTickMonitor-1.12-3.0.0.jar                            | None                                     |
	| UCHIJAAAA | sync                 | 7.0.0            | Sync-1.12.2-7.0.1.jar                                       | None                                     |
	| UCHIJAAAA | tesla                | 1.0.63           | Tesla-1.12.2-1.0.63.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | teslafied            | 1.1.1            | teslafied-1.12-1.1.1.jar                                    | None                                     |
	| UCHIJAAAA | beneath              | 1.3.0            | The Beneath-1.12.2-1.3.0.jar                                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAAAA | thermalcultivation   | 0.1.2            | ThermalCultivation-1.12.2-0.1.2.8-universal.jar             | None                                     |
	| UCHIJAAAA | thermaldynamics      | 2.3.7            | ThermalDynamics-1.12.2-2.3.7.14-universal.jar               | None                                     |
	| UCHIJAAAA | mysttmtgravitymod    | 2.8.0            | UpAndDownAndAllAround-1.12.2-2.8.0.jar                      | None                                     |
	| UCHIJAAAA | wanionlib            | 1.12.2-1.4       | WanionLib-1.12.2-1.4.jar                                    | None                                     |
	| UCHIJAAAA | wearablebackpacks    | 3.1.0            | WearableBackpacks-1.12.2-3.1.0.jar                          | None                                     |
	| UCHIJAAAA | worldedit            | 6.1.8            | worldedit-forge-mc1.12-6.1.8-dist.jar                       | None                                     |
	| UCHIJAAAA | unidict              | 1.12.2-2.1       | UniDict-1.12.2-2.1.jar                                      | None                                     |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-45.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
mysttmtgravitymod (UpAndDownAndAllAround-1.12.2-2.8.0.jar)
  uk.co.mysterymayhem.gravitymod.asm.Transformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b135.jar)
  
HammerCoreCore (HammerCore-1.12.2-1.9.5.7.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
EcomodLoadingPlugin (EcologyMod-1.12.2-1.4.0.0.jar)
  ecomod.asm.EcomodClassTransformer
GottaGoFastLoader (gottagofast-1.0.jar)
  com.thiakil.gottagofast.coremod.GottaGoFastASMTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	List of loaded APIs: 
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-3.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.12.2-2.1.1.3.b89.jar
		* BuildCraftAPI|fuels (2.0) from EcologyMod-1.12.2-1.4.0.0.jar
		* BuildCraftAPI|tiles (1.2) from EcologyMod-1.12.2-1.4.0.0.jar
		* BuildCraftAPI|tools (1.0) from EcologyMod-1.12.2-1.4.0.0.jar
		* cofhapi (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* ecomodapi (1.3) from EcologyMod-1.12.2-1.4.0.0.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.138.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* RefinedRelocationAPI (2.0.0) from RefinedRelocation_1.12.2-4.2.16.jar
		* SecurityCraftAPI (1.2.2) from [1.12.x] SecurityCraft v1.8.3.jar
	[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 
	0: Working: false |Last Profiler section: [UNKNOWN]| Interrupted:false

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:ON, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['LokeYourLord'/308, l='world', x=55,11, y=55,26, z=-75,61]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Artem226** [comment]
Hello, LokeYourLord! This bug has been fixed in the newer version of the mod. (1.12.2-1.4.1.0)

**Comment by Artem226** [comment]
Hello, LokeYourLord! This bug has been fixed in the newer version of the mod. (1.12.2-1.4.1.0)

**Comment by LokeYourLord** [comment]
Oh, thank you and sorry for the duplicate :D!
