### ISSUE TITLE
[1.7.10] Server crashes during pre-init

### ISSUE THREAD

**Issue by Plajdo** [Artem226/MinecraftEcologyMod#42]
I used 1.7.10 version of this mod on my server in a modpack, but it crashed during pre-init with this:

```
Exception in server tick loop
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
	at ecomod.core.stuff.EMItems.doPreInit(EMItems.java:47)
	at ecomod.core.stuff.MainRegistry.doPreInit(MainRegistry.java:59)
	at ecomod.core.EcologyMod.preInit(EcologyMod.java:91)
```

To me it looks like it's trying to load a class that is client-side only. Is the server supported in this version for 1.7.10, or should I use it only in singleplayer? There isn't any 1.7 branch on github, so I couldn't check the code and try to fix it myself 😃.

Thanks,
plajdo

**Comment by yoloSwagSEO** [comment]
Hello!
Sory for my english, the probleme is proxy dont use and the server has not render class.

I need source code pour patch this.
